<?php
// DO NOT EDIT THIS FILE!
// Your modifications go to config.local.inc.php4!
$version			= '20051108';

// If language detection fails, use that language as fallback.
$default_lang = 	$lang	= 'en';
$cfg['force_default_language']	= false;

// You may want to move some files to a second webserver
// in order to decrease the load on your SSL-enabled one.
// (Directories out of the client's browser's view.)
$cfg['images_dir']	= 'images';		// This is where you store all the images
$cfg['design_dir']	= 'design';		// CSS
$cfg['upload_dir']	= 'uploads';		// such as attachements

// Select one of: plain
$cfg['theme']		= 'plain';

// Copy this line and change it according to your environment.
/*
$i = 0;
$cfg['Servers']['verbose'][] = 'localhost';
$cfg['Servers']['number'][] = $i++;
$cfg['Servers']['DB'][] = array(
	'TYPE'	=> 'mysql',			// currently only mysql
	'HOST'	=> 'localhost',
	'USER'	=> '##MysqlUser##',
	'PASS'	=> '##MysqlSecret##',
	'DB'	=> '##MysqlDB##',
	'PREFIX'	=> ''			// prefix to table names
);
*/

?>